### ISSUE TITLE
ServerMock#matchPlayer() does not seem to work

### ISSUE THREAD

**Issue by EbonJaeger** [seeseemelk/MockBukkit#10]
I must be doing something wrong, but I can't figure out what.

My test class sets up the `ServerMock` before tests with `MockBukkit.mock()`, and five random players and two players with names I chose are added to the server.

I am attempting to unit-test my implementation of Discord-like mentions in chat. I have verified with println's that all players were added and are "online" on the server mock, and that the test mention used exactly matches the named player I want.

When this code is called from my chat listener:
```kotlin
val players = Bukkit.matchPlayer(mention)
```
the returned result has nothing in it; it is empty.

**Comment by seeseemelk** [comment]
What branch of MockBukkit are you using?
Can you also send the code for the unit test, the setup, and the teardown functions?
On my computer it seems to work so I'm not entirely certain what the issue seems to be.

**Comment by seeseemelk** [comment]
I have found the issue. It would not match any players unless your match string only contained lowercase characters.
This has now been fixed in v1.13 and v1.13-spigot.
