### ISSUE TITLE
Integrate with Maven Central

### ISSUE THREAD

**Issue by JarvisCraft** [seeseemelk/MockBukkit#12]
A positive feature for this project would be Maven Central integration by which I mean deploying releases to it (by hand or, better, by some CI like Travis). At current, the rules there allow publshing resources with 3-rd party repositories so this would not be a problem.
As another option I can suggest you some kind of partnership as I've got a group of minecraft-related utilities which are deployed to Maven Central at current so the projects can be joined into one single which will be altogether available in Maven Central as a group of various useful modules.

**Comment by Narimm** [comment]
I have built this against bukkit 1.13.2 and deployed it on our maven repo

https://maven.addstar.com.au/artifactory/ext-release-local/

**Comment by JarvisCraft** [comment]
I see, but I feel like it might be more comfortable to have it also deployed to Maven's central repository as it will ler developers add it to their projects without specifying your repo

**Comment by seeseemelk** [comment]
Sorry for such a late response, I have been incredibly busy lately.
I will try to get it on Maven Central, but I have never done something like that yet and I always assumed it wouldn't be used enough for it to be worth the hassle.
I'm glad I was wrong!

**Comment by seeseemelk** [comment]
I finally found the time to properly check this out, and I currently have an open ticket to receive a groupId on mavenCentral.

**Comment by seeseemelk** [comment]
I've published the first release on maven central, although it is still processing.
Expect this issue to be closed in a few hours once it's been fully processed and I have tested that it works as expected.

**Comment by seeseemelk** [comment]
This is now working. You can use v0.1.1 of MockBukkit-v1.13 and MockBukkit-v1.13-spigot (ignore MockBukkit-v1.13:0.1.0, this one is actually MockBukkit-v1.13-spigot, but I was still somewhat confused on how to properly release something on Sonatype).
