### ISSUE TITLE
Maven - switch and add POM.xml

### ISSUE THREAD

**Issue by Narimm** [seeseemelk/MockBukkit#15]
Not really an issue more so a suggestion if you do intend to deploy to maven central as per issue #12 my suggestion is to actually add a real pom.  I have converted my master branch fork to pure maven and removed gradle - primarily to integrate better with our development.  But there is a pom there that creates an uberjar for deployment as well as sources - I havent added javadocs but thats easy enough.   

I havent PR'd my master as its probable diverging enough now that you may not want everything - 

I have also added the ability to convert ChatColor to ANSI so people can visually check message formatting and colouring in tests.

**Comment by Narimm** [comment]
Oh no doubt - that wsnt my point...I see stacks of stuff published via gradle and the issue I have is the pom's are often incomplete - which is more people not using gradle properly - I dont find that gradle generates complete poms

**Comment by Narimm** [comment]
Its also why I forked the project ...I dislike gradle - my point was just that in my extensions to the consolesender mock I used jansi to mimic chatcolors in console ... that requires jansi shaded into the uberpom - now gradle can shade just fine...but it doesnt build the pom correctly to show the scope of dependencies imho.

**Comment by seeseemelk** [comment]
Sorry if I'm not responding often, I've been very busy with school lately and now a period of exams are coming up.
I don't think shading any external libraries into the MockBukkit jars is a good idea, it can make dependency management much worse if you are at the same time using different versions of those libraries in your plugins themselves. It's nice to do so for a plugin or an application, but MockBukkit is not a plugin, merely a library your IDE/testing script loads in during the testing phase. Therefore it doesn't need to be shaded and can rely on Maven for handling any dependencies.
Then again, I haven't used Maven all that much so I might be wrong on this.

**Comment by yannicklamprecht** [comment]
No need to shade something in. @Narimm You can simply generate a library using this library to extend functionality. I extended some of the stubs to implement functionality I need for a specific test.


By the way this project is more a StubBukkit instead of a MockBukkit.

**Comment by Narimm** [comment]
Fair point re shading.. i removed it from my build.
I reckon you could debate stub v mock - there is a lot of crossover - 
and in this case we are verifying behaviours in some cases more so than state. 
In the end its just a name.

**Comment by Narimm** [comment]
@yannicklamprecht if the extensions you are making replicate a bukkit server behaviour you should consider patching them back into the master library.  In this way we flesh out the test suite

**Comment by seeseemelk** [comment]
I think MockBukkit sounds a bit better than StubBukkit, but that might just be personal preference (and the fact that I'm probably more used to it). I will not be converting it from gradle to maven as I personally do all my projects (both Bukkit and other) in gradle, though the latest commit supports the `install` and `uploadArchives` task which will store MockBukkit in the local maven repository and on Sonatype respectively.
