### ISSUE TITLE
Using runTaskTimer with a 0 delay doesnt execute the first cycle.

### ISSUE THREAD

**Issue by Narimm** [seeseemelk/MockBukkit#20]
`BukkitTask task = Bukkit.getScheduler().runTaskTimer(plugin, this::doTimer, 0, 20L); `

This creates a repeating task with a scheduledtick at 0 but the current tick is 0 yet it doesnt actually trigger the task instantly.

Hence it appears the task wont trigger.

```		AtomicInteger count = new AtomicInteger(0);
		Runnable callback = () -> count.incrementAndGet();
		BukkitTask task = scheduler.runTaskTimer(null, callback, 0, 2L);
		assertNotNull(task);
		assertEquals(0, count.get());
		scheduler.performTicks(1L);
		assertEquals(1, count.get());```
will cause a test failure. Actually the first assert should fail but it doesnt ...the second fails.

**Comment by MiniDigger** [comment]
mmmmh, from looking at CB code (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/scheduler/CraftScheduler.java) this behavior is in line with what CB does. scheduling a task does never instantly execute it, only the next tick will process it, so this isn't a bug.

**Comment by Narimm** [comment]
so setting a 0 delay in theory shouldnt be possible?

**Comment by Narimm** [comment]
Because the issue here is that the task.scheduledtick will be set to 0...and never trigger.

**Comment by Narimm** [comment]
```		BukkitTask task = scheduler.runTaskTimer(null, callback, 0, 2L);
		assertNotNull(task);
		assertEquals(0, count.get());
		scheduler.performTicks(2L);
		assertEquals(1, count.get());
```
This fails as well.

**Comment by Narimm** [comment]
`RepeatingTask repeatingTask = new RepeatingTask(id++, plugin, true, currentTick + delay, period, task);`
I think the scheduled tick should be currenttick+delay+period

**Comment by seeseemelk** [comment]
I have made a new branch where I added a unit test testing this exact behaviour.
However, I don't feel comfortable fixing this as it is a bit of an edge case and I haven't verified yet how CraftBukkit handles it;
