### ISSUE TITLE
Support ItemStack#setUnbreakable 

### ISSUE THREAD

**Issue by tatanpoker09** [seeseemelk/MockBukkit#23]
Hey, I wish I could contribute, I sincerely have no idea how nbt tags are set internally though :( Is there any way you guys could implement this?
(Along with the isUnbreakable counterpart, of course)

**Comment by seeseemelk** [comment]
I added the feature and published a new archive. I did notice that the current archive on maven central is still for 1.13, not 1.14. The feature I added to 1.14. Do you want me to backport this to 1.13 or is 1.14 good for you?

**Comment by tatanpoker09** [comment]
1.14 is good, I think I can read the code and backport it myself if necessary, thanks!
