### ISSUE TITLE
Add support for World#spawnEntity

### ISSUE THREAD

**Issue by tatanpoker09** [seeseemelk/MockBukkit#25]

**Comment by tatanpoker09** [comment]
Thanks! If given indications though, I can try to implement it myself and send a pull request

**Comment by seeseemelk** [comment]
If you could implement this, that would be awesome because I don't think I'll have enough time soon. If you add this, could you also add some unit tests for this method? Having a unit testing framework with bugs/regressions in it is quite annoying.

**Comment by tatanpoker09** [comment]
Yeah sure, I always try to add unit tests (as long as I know how to implement it. Do you know where I can get some info on how to implement? Maybe similar to how players are added?

**Comment by tatanpoker09** [comment]
Update: I sent a pull request #26 for this.

**Comment by seeseemelk** [comment]
The pull request is merged and an update was pushed to maven central
