### ISSUE TITLE
player join event not fired

### ISSUE THREAD

**Issue by ThePhilderbeast** [seeseemelk/MockBukkit#30]
player joined events are not fired when adding players to mock sever

sample test:
```java
    @Test
    public void playerJoin()
    {
        PlayerMock player = server.addPlayer();

        pluginManager.assertEventFired(event -> { return event instanceof PlayerJoinEvent; });
    }
```

**Comment by tatanpoker09** [comment]
I sent a fix. Its in my old pull request, I guess we'll have to wait for @seeseemelk to have some free time

**Comment by ThePhilderbeast** [comment]
@tatanpoker09 your fix dosent pass this test either.

**Comment by seeseemelk** [comment]
I have accepted that pull request, but I'm not sure that it is a good idea to always fire that event.
If you restart the plugin while the server is running, that event is not fired for anyone still playing on the server.

My suggestion is to add a method called `joinPlayer`;
This method would work in the exact same way as `addPlayer`, except that it would fire a `PlayerJoinEvent`.
It would keep the behaviour of `addPlayer` the same, and make it possible to unit test plugins against both server starts and restarts.

Would this work for you?

**Comment by tatanpoker09** [comment]
Yeah that sounds like a better solution. I'll try to do that during the night, if you decide to work on this on your own though please let me know

**Comment by seeseemelk** [comment]
I might work on this tomorrow, once I get back from work. But I have to sleep now, I have to get up early tomorrow and it's already way too late.

**Comment by tatanpoker09** [comment]
> @tatanpoker09 your fix dosent pass this test either.

https://github.com/seeseemelk/MockBukkit/blob/v1.14/src/test/java/be/seeseemelk/mockbukkit/entity/PlayerMockTest.java The same test is added here at the end of the file. It passed for me, can you show under what context it is failing?

**Comment by ThePhilderbeast** [comment]
so its not passing through to the join player event of the plugin getting mocked, i think this is because your not calling it on the mock player mamanger possisble, ill investigate more tonight

**Comment by tatanpoker09** [comment]
I just tested it with a local plugin I'm using. The join player event of the plugin is indeed called. Are you sure you have registered the event to the plugin manager? Does it work on a normal bukkit server?

**Comment by seeseemelk** [comment]
I've create #32 
Does this pull request solve your issue? It adds a `joinPlayer` method that will fire the event, allowing for more flexible testing.

**Comment by ThePhilderbeast** [comment]
https://github.com/ThePhilderbeast/AutoPickup/blob/master/src/test/java/com/philderbeast/autopickup/AutoPickupPluginTest.java

this test is still failing and i have no idea why with these changes

**Comment by seeseemelk** [comment]
I'm unable to replicate this issue. If this is still present, would you be able to create a small java project that has this failing test. Such as project would only need a dependency on Bukkit and MockBukkit. No need to write a `plugin.yml` or anything like that, unless it is part of the cause.

**Comment by ThePhilderbeast** [comment]
I havent looked at this for some time, if you cant reproduce it ill close it for now, and re-open if I look at it an reproduce.
