### ISSUE TITLE
Update readme build.gradle instructions

### ISSUE THREAD

**Issue by Markyroson** [seeseemelk/MockBukkit#36]
Currently IntelliJ cannot resolve `com.github.seeseemelk:MockBukkit-v1.13:0.1.1-SNAPSHOT` (mavenCentral() being a listed repository). Could you please update the readme instructions for installation? @seeseemelk

**Comment by MiniDigger** [comment]
snapshots arent on central, snapshots go to https://oss.sonatype.org/content/repositories/snapshots/

I would recommend you to just use the latest version instead https://mvnrepository.com/artifact/com.github.seeseemelk/MockBukkit-v1.13

**Comment by Markyroson** [comment]
Thanks @MiniDigger ! In that case, then the readme is currently incorrect and definitely does need an update.

**Comment by seeseemelk** [comment]
The latest version is at this moment actually `com.github.seeseemelk:MockBukkit-v1.14:0.2.1`.
But I'll update the readme later today.

**Comment by seeseemelk** [comment]
This is fixed in #40
