### ISSUE TITLE
Update wiki home page

### ISSUE THREAD

**Issue by Markyroson** [seeseemelk/MockBukkit#37]
The instructions within https://github.com/seeseemelk/MockBukkit/wiki are currently out of date as 'com.github.seeseemelk:MockBukkit:master-SNAPSHOT' does not currently resolve, even with `maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }` in the build.gradle file.

This is closely related to #36

**Comment by seeseemelk** [comment]
I've updated the readme to contain more current information, as well as let the reader know that possibly more correct information can be found in the `README.md` as it might change depending on the version of MockBukkit you are using.

**Comment by Markyroson** [comment]
Perfect. Thank you so much :)
