### ISSUE TITLE
Update PlayerMock wiki page

### ISSUE THREAD

**Issue by Markyroson** [seeseemelk/MockBukkit#38]
The instructions for customising the object before adding it are currently incorrect. My IDE tells me `Cannot resolve constructor 'PlayerMock(java.lang.String)'`

**Comment by Markyroson** [comment]
This appears to have been replaced with `PlayerMock player = server.addPlayer("");`

**Comment by seeseemelk** [comment]
Thanks for reporting this! It's fixed now.
