### ISSUE TITLE
Loading plugin dependencies

### ISSUE THREAD

**Issue by Markyroson** [seeseemelk/MockBukkit#39]
If your plugin relies on another plugin, how do you load a version of that one for the tests?

**Comment by seeseemelk** [comment]
This is something that I have been wanting to add, but I haven't yet as I didn't have a need for it. Currently you will have to stub out the parts that require external plugins.
I will look into adding this later today, but as this is a relatively complex issue it might take some time to do this.

**Comment by seeseemelk** [comment]
I had written a long post about this, and near the end of it I actually found that solution 3 would probably work quite well.
So this post is pretty much a ramble about nothing, but I'm posting it here anyway.

---
I've been thinking about this; it wouldn't be super hard to implement.

There is, however, one issue that I've found: where do you get the dependency jar files?
I can think of three 'solutions', each have there own issues:
- You can add the jar files to your directory and check them into git. This would allow contributors easily get started testing your plugins. However, this would require that all dependency plugins have a license allowing you to publish the jar (some - like GPL or Expat - allow this, but many other licenses don't).
- You can add the jar files to your directory but not add them to git. This allows plugin authors to stay clear of any licensing issues. The only problem is that anyone wanting to contribute to your project would have to find every dependency, download them and place them in the right directory. This makes it significantly harder for contributors to get started, and would make it quite difficulty to check your project into a CI/CD system.
- You can have some Gradle/Maven plugin that will automatically download the dependencies from the internet. Easier for plugin contributors and CI/CD systems to use, but harder for a plugin author to set up in Gradle/Maven.

**Comment by Markyroson** [comment]
I think that solution 3 would work quite well as well. I do hope that this gets added :)

I tried to compile my own MockBukkit from source, but it (in use) then has the habit of deciding that code is going to randomly break and not function/throw random errors pre-compile....like saying load() doesn't take a class as a parameter, it takes a class as a parameter..... Anyhoo, rambling of my own haha.

**Comment by seeseemelk** [comment]
I think I've got this working. I opened a pull request (#49)  that adds a `MockBukkit.loadJar(string pathToJar)`, which will open the jar file and load the plugin into the mock server.
I've implemented the plugin for the v1.15 branch, as it is currently the latest bukkit version. If you need me I can backport it to the v1.14 branch. There are a couple of changes that have happened in the `UnsafeValues` class that made things a bit more annoying.

Anyway, you can try it out the `feature/multi-project` branch. I haven't properly tested it, so I'm not yet going to merge it until I know that it works.

**Comment by Markyroson** [comment]
The 1.15 branch is fine. Thank you so much!! I haven't ever been able to properly build the library (this repo) myself locally to test anything. :( What it does is simply tell me that it has no MockBukkit.load() method that accepts a .class whenever I custom build a mockbukkit jar

Cannot resolve method 'load(java.lang.Class<me.markyroson.markycraftallinone.Main>)

yet using gradle? Works fine...I just cant build myself and have it recognize it.

**Comment by seeseemelk** [comment]
I'm closing this because the pull request got merged, so support for this is now available

**Comment by LockedThread** [comment]
Could we revive this? The PR is stale, and this needs more of a necessity than an enhancement for most people.
