### ISSUE TITLE
[Feature Request] Support for asynchronous tasks

### ISSUE THREAD

**Issue by NexAdn** [seeseemelk/MockBukkit#7]
I'd really like to see support for asynchronous repeating tasks, especially `BukkitSchedule#runTaskTimerAsynchronously(Plugin, Runnable)`, as I need those for one of my plugins.

Thank you in advance

**Comment by seeseemelk** [comment]
I have added this to the v1.13 and v1.12 version of MockBukkit.
https://github.com/seeseemelk/MockBukkit/commit/6681740822d1a43629f2a947a6ef7d76755d16a7
Happy testing!
